# Generated by Django 4.2.1 on 2023-05-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jop', '0003_jop_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jop',
            name='Vacancy',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='jop',
            name='experience',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='jop',
            name='published_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jop',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
